.\" Man page for aoeui
.\"
.\" Copyright 2007 Peter Klausler
.\" Released under GPLv2.
.TH aoeui 1 "March 17, 2007"
.LO 1
.SH NAME
aoeui \- a lightweight visual editor optimized for Dvorak
.SH SYNOPSIS
.B aoeui
.RI [ file... ]
.SH DESCRIPTION
.B aoeui
is an interactive display text editor optimized for users of the
Dvorak keyboard layout.
.SH COMMANDS
.B aoeui
run with no file name arguments displays a short command
introduction and summary.
.SH ENVIRONMENT
.TP
.B SHELL
is used to name the program run by the ^E command.
.SH FILES
.TP
.IB file ~
is overwritten with the original contents of
.IR file .
.SH AUTHOR
Peter Klausler <peter@klausler.com> wrote
.BR "aoeui" .
